### ISSUE TITLE
about C2D baseline

### ISSUE THREAD

**Issue by thesmalll** [tea1528/Non-Local-NN-Pytorch#2]
Can we add a three-dimensional non-local block to a two-dimensional convolution? For example, insert three-dimensional non-local block in the resnet2D.

**Comment by tea1528** [comment]
Hi, I've checked by running resnet2D with 3D non-local block.

You'd get an error message as follows:
`RuntimeError: Expected 5-dimensional input for 5-dimensional weight [16, 32, 1, 1, 1], but got 4-dimensional input of size [128, 32, 16, 16] instead`

Due to dimension error, I don't recommend adding the 3D non-local block for C2D. Furthermore, as mentioned by the original paper C2D doesn't have any 3D convolutional operation and only has the temporal max pooling.

Thank you!
